export const TOPIC_CATEGORY_CONSTANTS = {
    ERROR: {
        CREATED_FAIL: "CREATED_FAIL",
        NOT_FOUND: "NOT_FOUND",
        UPDATE_FAIL: "UPDATE_FAIL",
        DELETE_FAIL: "DELETE_FAIL",
        ACTION_FORBIDDEN: "ACTION_FORBIDDEN",
        EXISTED: "EXISTED",
    }
};